server:
  port: 2000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
  instance:
    prefer-ip-address: true
    instance-id: http://localhost:2000
spring:
  application:
    name: product-service