server:
 port: 1001
spring:
 application:
  name: zipkin-server
management:
  metrics:
    web:
      server:
        auto-time-requests: false
#eureka:
# client:
#  serviceUrl:
#   defaultZone: http://localhost:1000/eureka/