server:
  port: ${prod1.eureka.server.port}    # 指定该Eureka实例的端⼝

eureka:
  environment: prod
  datacenter: linux
  server:
    enable-self-preservation: true  # 关闭自我保护
  instance:
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
#    prefer-ip-address: true   # 这个设置成true后， unavailable-replicas '异常'
    hostname: ${prod1.eureka.hostname}    # 指定该Eureka实例的主机名
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${prod2.eureka.hostname}:${prod2.eureka.server.port}/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@${prod3.eureka.hostname}:${prod3.eureka.server.port}/eureka/


