server:
  port: ${prod3.eureka.server.port}    # 指定该Eureka实例的端⼝

eureka:
  environment: prod
  datacenter: linux
  server:
    enable-self-preservation: true  # 关闭自我保护
  instance:
    hostname: ${prod3.eureka.hostname} # 指定该Eureka实例的主机名
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
#    prefer-ip-address: true  # 这个设置成true后， unavailable-replicas '异常'
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${prod1.eureka.hostname}:${prod1.eureka.server.port}/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@${prod2.eureka.hostname}:${prod2.eureka.server.port}/eureka/
